#!/bin/bash

HOME=$(pwd)
URL="http://anduin.linuxfromscratch.org/files/BLFS/svn/xorg/lib-7.4.wget"
TMP=$(mktemp -d)
FILE=$(basename $URL)
cd $TMP && wget -q $URL

if ! grep -q pixman $FILE
then
	echo "pixman-0.13.2.tar.bz2" >> $FILE
fi

echo "# This file auto generated by $0" >> filelist

i=101
for file in $(grep -v '^#' $TMP/$FILE)
do
	wget -q http://kerrek.linuxfromscratch.org/pub/blfs/conglomeration/Xorg-lib/$file
	echo '' >> filelist
	echo "FILE$i= $file" >> filelist
	echo "URL-\$(FILE$i)= \$(URLBASE)/\$(FILE$i)" >> filelist
	echo "SHA-\$(FILE$i)= $(sha1sum $file | awk '{print $1}')" >> filelist
	i=`expr $i + 1`
done

mv filelist $HOME
cd $HOME
rm -rf $TMP
