#!/bin/sh
LABEL="LFS_CD"
DEVS=`echo /dev/hd* /dev/scd*`

while [ -z "$CDROM" ] && [ "$TIMEOUT" != "..............." ] ; do
	for DEV in $DEVS ; do
		if [ "`isoinfo -V $DEV 2>/dev/null`" = "$LABEL" ] ; then
			CDROM=$DEV
		fi
	done
	if [ -z "$CDROM" ] ; then
		echo -n "."
		TIMEOUT=".$TIMEOUT"
		sleep 1
	fi
done

if [ -z "$CDROM" ] ; then
	echo "Cannot find LFS Live CD."
	echo "This probably means that your IDE or SCSI controller is not supported."
	exit 1
else
	echo "LFS Live CD is $CDROM"
fi

mount -w -t tmpfs -o size=90% tmpfs /.tmpfs
mkdir /.tmpfs/.overlay

# Probably redundant, but might be useful in the future for ejecting the CD
mkdir -p /.tmpfs/.overlay/dev/shm /.tmpfs/.overlay/proc
mkdir -m1777 /.tmpfs/.overlay/tmp

mkdir /.tmpfs/.cdrom
mkdir /.tmpfs/.sqfs

# Work around unionfs bug that causes tst-cancel16 glibc test to fail in Ch5
mkdir -m1777 /.tmpfs/.tmp

mount -r -t iso9660 $CDROM /.tmpfs/.cdrom
losetup /dev/loop0 /.tmpfs/.cdrom/.root.sqfs
mount -r -t squashfs /dev/loop0 /.tmpfs/.sqfs

# File locking and mmap don't work well on unionfs 1.0.11, this breaks
# module-init-tools.
# Fixed in unionfs 1.0.12a, but that version is oopsy when overwriting files.
MODDIR=`echo /.tmpfs/.sqfs/lib/modules/*`
MODDIR=${MODDIR#/.tmpfs/.sqfs/}
mkdir -p /.tmpfs/.overlay/$MODDIR
ln -s /dev/shm/.sqfs/$MODDIR/kernel /.tmpfs/.overlay/$MODDIR

insmod /lib/unionfs.ko
mount -w -t unionfs -o dirs=/.tmpfs/.overlay=rw:/.tmpfs/.cdrom=ro:/.tmpfs/.sqfs=ro unionfs /.union
mount -o move /.tmpfs /.union/dev/shm

ln -s $CDROM /.union/dev/lfs-cd

# Work around unionfs bug that causes tst-cancel16 glibc test to fail in Ch5
mount -o bind /.union/dev/shm/.tmp /.union/tmp

exec run-init /.union /sbin/init
