alias ls='ls --color=auto'
eval $(dircolors -b /etc/dircolors)

# Colors for PS1
RED="\[\033[0;31m\]"
GREEN="\[\033[0;32m\]"
ORANGE="\[\033[0;33m\]"
BRWHITE="\[\033[0;38m\]"
WHITE="\[\033[00m\]"

# Prompt
if [ `whoami` == "root" ] ; then
	PS1="${BRWHITE}\h:$RED\u | $BRWHITE\@ \d $RED| $GREEN\w$BRWHITE\n$WHITE\\$ "
else
	PS1="$BRWHITE\h:$GREEN\u | $ORANGE\@ $BRWHITE\d $GREEN| \w\n$BRWHITE\\$ $WHITE"
fi

export PS1
