7007Available locales (page 2 of 2)

fr_CA.ISO-8859-1         lt_LT.ISO-8859-13        sk_SK.ISO-8859-2
fr_CH.ISO-8859-1         lv_LV.ISO-8859-13        sl_SI.ISO-8859-2
fr_FR.ISO-8859-1         mi_NZ.ISO-8859-13        so_DJ.ISO-8859-1
fr_FR.ISO-8859-15@euro   mk_MK.ISO-8859-5         so_KE.ISO-8859-1
fr_LU.ISO-8859-1         ms_MY.ISO-8859-1         so_SO.ISO-8859-1
fr_LU.ISO-8859-15@euro   mt_MT.ISO-8859-3         sq_AL.ISO-8859-1
ga_IE.ISO-8859-1         nb_NO.ISO-8859-1         st_ZA.ISO-8859-1
ga_IE.ISO-8859-15@euro   nl_BE.ISO-8859-1         sv_FI.ISO-8859-1
gd_GB.ISO-8859-15        nl_BE.ISO-8859-15@euro   sv_FI.ISO-8859-15@euro
gl_ES.ISO-8859-1         nl_NL.ISO-8859-1         sv_SE.ISO-8859-1
gl_ES.ISO-8859-15@euro   nl_NL.ISO-8859-15@euro   tg_TJ.KOI8-T
gv_GB.ISO-8859-1         nn_NO.ISO-8859-1         tl_PH.ISO-8859-1
hr_HR.ISO-8859-2         oc_FR.ISO-8859-1         uk_UA.KOI8-U
hu_HU.ISO-8859-2         om_KE.ISO-8859-1         uz_UZ.ISO-8859-1
id_ID.ISO-8859-1         pl_PL.ISO-8859-2         wa_BE.ISO-8859-1
is_IS.ISO-8859-1         pt_BR.ISO-8859-1         wa_BE.ISO-8859-15@euro
it_CH.ISO-8859-1         pt_PT.ISO-8859-1         xh_ZA.ISO-8859-1
it_IT.ISO-8859-1         pt_PT.ISO-8859-15@euro   zu_ZA.ISO-8859-1
it_IT.ISO-8859-15@euro   ro_RO.ISO-8859-2         
kl_GL.ISO-8859-1         ru_RU.ISO-8859-5         
kw_GB.ISO-8859-1         ru_RU.KOI8-R             
lg_UG.ISO-8859-10        ru_UA.KOI8-U             



[F1] = options  [F2] = locales, page 1  [F3] = locales, page 2  [F4] = keymaps

