7007Available locales (page 1 of 2)

aa_DJ.ISO-8859-1         en_AU.ISO-8859-1         es_ES.ISO-8859-15@euro
af_ZA.ISO-8859-1         en_BW.ISO-8859-1         es_GT.ISO-8859-1
an_ES.ISO-8859-15        en_CA.ISO-8859-1         es_HN.ISO-8859-1
be_BY.CP1251             en_DK.ISO-8859-1         es_MX.ISO-8859-1
bg_BG.CP1251             en_GB.ISO-8859-1         es_NI.ISO-8859-1
br_FR.ISO-8859-1         en_HK.ISO-8859-1         es_PA.ISO-8859-1
br_FR.ISO-8859-15@euro   en_IE.ISO-8859-1         es_PE.ISO-8859-1
bs_BA.ISO-8859-2         en_IE.ISO-8859-15@euro   es_PR.ISO-8859-1
ca_ES.ISO-8859-1         en_NZ.ISO-8859-1         es_PY.ISO-8859-1
ca_ES.ISO-8859-15@euro   en_PH.ISO-8859-1         es_SV.ISO-8859-1
cs_CZ.ISO-8859-2         en_SG.ISO-8859-1         es_US.ISO-8859-1
da_DK.ISO-8859-1         en_US.ISO-8859-1         es_UY.ISO-8859-1
de_AT.ISO-8859-1         en_ZA.ISO-8859-1         es_VE.ISO-8859-1
de_AT.ISO-8859-15@euro   en_ZW.ISO-8859-1         et_EE.ISO-8859-1
de_BE.ISO-8859-1         es_AR.ISO-8859-1         et_EE.ISO-8859-15
de_BE.ISO-8859-15@euro   es_BO.ISO-8859-1         eu_ES.ISO-8859-1
de_CH.ISO-8859-1         es_CL.ISO-8859-1         eu_ES.ISO-8859-15@euro
de_DE.ISO-8859-1         es_CO.ISO-8859-1         fi_FI.ISO-8859-1
de_DE.ISO-8859-15@euro   es_CR.ISO-8859-1         fi_FI.ISO-8859-15@euro
de_LU.ISO-8859-1         es_DO.ISO-8859-1         fo_FO.ISO-8859-1
de_LU.ISO-8859-15@euro   es_EC.ISO-8859-1         fr_BE.ISO-8859-1
el_GR.ISO-8859-7         es_ES.ISO-8859-1         fr_BE.ISO-8859-15@euro



[F1] = options  [F2] = locales, page 1  [F3] = locales, page 2  [F4] = keymaps

