7007The following keymaps are available on this CD:

azerty:
azerty be-latin1 fr-latin1 fr-latin9 fr fr-pc wangbe wangbe2

dvorak:
ANSI-dvorak dvorak-l dvorak/dvorak dvorak-r

fgGIod:
tr_f-latin5 trf

qwerty:
bg_bds-cp1251 bg-cp1251 bg_pho-cp1251 br-abnt br-abnt2 br-latin1-abnt2
br-latin1-us by2_win cf cz-cp1250 cz-lat2 cz-lat2-prog cz dk-latin1 dk
es et et-nodeadkeys fi-latin1 fi-latin9 fi gr gr-pc hu101
il-heb il il-phonetic is-latin1 is-latin1-us it it-ibm it2 jp106
la-latin1 lt.baltic lt.l4 mk0 mk-cp1251 mk nl nl2 no-latin1 no
pc110 pl pl2 pt-latin1 pt-latin9 ro_win ru1 ru3 ru4 ru-ms ru-yawerty
se-ir209 se-lat6 sk-prog-qwerty sk-qwerty sr-cy sv-latin1 tralt tr_q-latin5
trq ua ua-ws uk us-acentos us

qwertz:
croat cz-us-qwertz de_CH-latin1 de-latin1 de-latin1-nodeadkeys de fr_CH-latin1
fr_CH hu sg-latin1-lk450 sg-latin1 sg sk-prog-qwertz sk-qwertz slovene



[F1] = options  [F2] = locales, page 1  [F3] = locales, page 2  [F4] = keymaps

