alias ls='ls --color=auto'
eval $(dircolors -b /etc/dircolors)

# Colors for PS1
RED="\[\033[0;31m\]"
GREEN="\[\033[0;32m\]"
ORANGE="\[\033[0;33m\]"
BOLD="\[\033[0;38m\]"
WHITE="\[\033[00m\]"

# Prompt
if [ $UID = 0 ] ; then
	PS1="$BOLD\h:$RED\u | $BOLD\D{%c} $RED| \w\n$BOLD\\$ $WHITE"
else
	PS1="$BOLD\h:$GREEN\u | $BOLD\D{%c} $GREEN| \w\n$BOLD\\$ $WHITE"
fi

export PS1
