#!/bin/bash
#
# Script for interactively choosing a network service
# and starting eth0 on the LFS 6.0 bootcd.
#
# Written by Jeremy Huntwork 09.17.2004
#

DIR=/etc/sysconfig/network-devices
ETH0CFG=$DIR/ifconfig.eth0
IFUP=$DIR/ifup
IFDOWN=$DIR/ifdown
LINKTEST=`ip link show eth0 2> /dev/null`
GREETING="Let's configure your network device!"

# Function to set nameservers in /etc/resolv.conf
# Allows user to enter any number of nameservers,
# exits when user types "done"

set_dns(){

	echo "Enter a DNS server: "
	echo "(Enter server addresses, one per line in order of preference, and type \"done\" when finished."
	read DNS
	counter=0
	while [ $DNS != "done" ]
	do
		# Check that user enters four numbers separated by '.'
		if [ -z "$DNS" -o -n "${DNS##?*.?*.?*.?*}" ] ; then
			echo "$DNS is not a valid nameserver address."
		else
			# If this is the first entry, overwrite any existing
			# /etc/resolv.conf, else append.
			if [ $counter -eq 0 ] ; then
				echo "nameserver $DNS" > /etc/resolv.conf
			else 
				echo "nameserver $DNS" >> /etc/resolv.conf
			fi
		fi
		read DNS
		counter=`expr $counter + 1`
	done
}		

set_static_ip(){
	echo "Enter your IP address:"
	read IP
	if [ -z "$IP" -o -n "${IP##?*.?*.?*.?*}" ] ; then
		echo ""
		echo "$IP is not a valid IP address."
		set_static_ip;
	else
		echo "IP=$IP" >> $ETH0CFG
	fi
}

set_static_gateway(){
	echo "Enter your default gateway:"
	read GTWY
	if [ -z "$GTWY" -o -n "${GTWY##?*.?*.?*.?*}" ] ; then
		echo ""
		echo "$GTWY is not a valid default gateway."
		set_static_gateway;
	else
		echo "GATEWAY=$GTWY" >> $ETH0CFG
	fi
}

set_static_prefix(){
	echo "Enter your prefix: "
	echo "(This determines your subnet mask. For example, a prefix of 24 would give you a subnet mask of 255.255.255.0)"
	read PRFX
	# First verify that user has entered a prefix, and not just pressed 'Enter'
	if [ $PRFX ] ; then
		# Check that prefix is a value between 8 & 30
		if [ "$PRFX" -lt 8 -o "$PRFX" -gt 30 ] ; then
			echo ""
			echo "$PRFX is not a valid prefix."
			set_static_prefix;
		else
			echo "PREFIX=$PRFX" >> $ETH0CFG
		fi
	else
		echo "Prefix cannot be empty."
		echo ""
		set_static_prefix;
	fi
}

set_static_broadcast(){
	echo "Enter your broadcast address: "
	read BRDCST
	if [ -z "$BRDCST" -o -n "${BRDCST##?*.?*.?*.?*}" ] ; then
		echo ""
		echo "$BRDCST is not a valid broadcast address."
		set_static_broadcast;
	else
		echo "BROADCAST=$BRDCST" >> $ETH0CFG
	fi
}

# Main function. Presents user with a choice of
# static or dhcp and attempts to bring up eth0

choose_service(){

	# Remove all previous configs, so ifup won't get confused.
	rm -f $DIR/ifconfig.eth0/*

	echo ""
	echo "What type of service should eth0 use?"
	echo "(static, dhcp or pppoe)"
	read SERVICE

case "$SERVICE" in

	dhcp) 
		echo "SERVICE=dhcpcd" > $ETH0CFG
		echo "DHCP_START=\"\"" >> $ETH0CFG
		echo "DHCP_STOP=\"-k\"" >> $ETH0CFG

		# Start the service
		$IFUP eth0

		# Test if dhcp worked and did not set DNS.
		# If so run set_dns function.
		if echo `ip link show eth0 2> /dev/null` | grep -q UP ; then			
			if [ ! -f /etc/resolv.conf ] ; then
				echo "DHCP did not configure DNS."
				set_dns;
			fi
			ip addr show eth0
		fi
		;;

	static)
		echo "SERVICE=ipv4-static" > $ETH0CFG
		set_static_ip;
		set_static_gateway;
		set_static_prefix;
		set_static_broadcast;
		set_dns;
		# Start the service
		$IFUP eth0
		;;

	pppoe)
		adsl-setup
		;;

	*)
		# Error message in case user entered something unusable, like "waldo"
		echo ""
		echo "--------------------------"
		echo " Invalid option: $SERVICE"
		echo " Please try again."
		echo "--------------------------"
		choose_service;
		;;
esac
}

# Script starts here. Tests first for link on eth0

if [ -n "$LINKTEST" ] ; then

	# If link is not up, start main function choose_service.

	if ! echo "$LINKTEST" | grep -q UP ; then
		echo ""
		echo $GREETING
		choose_service;
	else

	# If link is up, user likely has run this script already.
	# Take down eth0 so we can set it up cleanly.

		$IFDOWN eth0
		echo ""
		echo $GREETING
		choose_service;
	fi
else
	echo "Device eth0 is not present on this system!"
fi
