#!/bin/bash

TAR=`which tar` || exit 1
VRS=`$TAR --version | head -n 1 | awk '{print $4}' | cut -f2 -d'.'`

if [ -z $1 ] ; then
	echo "Error: No file specified."
	exit 1
fi

if [ ! -f $1 ] ; then
	echo "Error: File \"$1\" not found."
	exit 1
fi

if [ $VRS -lt 15 ] ; then # This version of tar doesn't support the automatic discovery of
			  # compression type.

	if echo $1 | grep -q "tar.gz" || echo $1 | grep -q ".tgz" ; then
		$TAR -xzf $1 || echo "Error: Unpacking of \"$1\" failed."
	elif echo $1 | grep -q "tar.bz2" ; then
		$TAR -xjf $1 || echo "Error: Unpacking of \"$1\" failed."
	elif [ `expr "$1" : '.*\(...\)'` = "tar" ] ; then
		$TAR -xf $1 || echo "Error: Unpacking of \"$1\" failed."
	else
		echo "Error: Bad format or unknown compression type"
	fi
else
	$TAR -xf $1 || echo "Error: Unpacking of \"$1\" failed."
fi
