#!/bin/sh
LABEL="LFS_CD"
DEVS=`echo /dev/hd* /dev/scd*`

while [ -z "$CDROM" ] && [ "$TIMEOUT" != "..............." ] ; do
	for DEV in $DEVS ; do
		if [ "`isoinfo -V $DEV 2>/dev/null`" = "$LABEL" ] ; then
			CDROM=$DEV
		fi
	done
	if [ -z "$CDROM" ] ; then
		echo -n "."
		TIMEOUT=".$TIMEOUT"
		sleep 1
	fi
done

if [ -z "$CDROM" ] ; then
	echo "Cannot find LFS Live CD."
	echo "This probably means that your IDE or SCSI controller is not supported."
	exit 1
else
	echo "LFS Live CD is $CDROM"
fi

mount -w -t tmpfs -o size=90% tmpfs /.tmpfs
mkdir /.tmpfs/.overlay

# Probably redundant, but might be useful in the future for ejecting the CD
mkdir /.tmpfs/.overlay/dev
mkdir /.tmpfs/.overlay/dev/shm
mkdir /.tmpfs/.overlay/proc

mkdir /.tmpfs/.cdrom
mkdir /.tmpfs/.sqfs
mount -r -t iso9660 $CDROM /.tmpfs/.cdrom
losetup /dev/loop0 /.tmpfs/.cdrom/root.sqfs
mount -r -t squashfs /dev/loop0 /.tmpfs/.sqfs
insmod /lib/unionfs.ko
mount -w -t unionfs -o dirs=/.tmpfs/.overlay=rw:/.tmpfs/.cdrom=ro:/.tmpfs/.sqfs=ro unionfs /.union
mount -o move /.tmpfs /.union/dev/shm
exec run-init /.union /sbin/init
