#!/bin/bash

if [ ! -f /bin/uname.real ] && [ ! -f /tools/bin/uname.real ]
then
	REAL="/bin/uname"
else
	REAL="uname.real"
fi

if echo `$REAL -m` | grep -q "i*86" ; then
	$REAL "$@" | sed 's/[56]86/486/'
elif echo `$REAL -m` | grep -q "sparc" ; then
	$REAL "$@" | sed 's/sparc64/sparc/'
else
	$REAL "$@"
fi
